export const types = {
    FETCH_CHARACTERS_REQUEST: 'FETCH_CHARACTERS_REQUEST',
    FETCH_CHARACTERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
    FETCH_CHARACTERS_ERROR: 'FETCH_CHARACTERS_ERROR',
    FETCH_CAT_SUCCESS: 'FETCH_CAT_SUCCESS',
    FETCH_JOKES_SUCCESS: 'FETCH_JOKES_SUCCESS',
}