export const types = {
    FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
    FETCH_HARRY_SUCCESS: 'FETCH_HARRY_SUCCESS',
    FETCH_QUOTES_SUCCESS: 'FETCH_QUOTES_SUCCESS',
    FETCH_CAT_SUCCESS: 'FETCH_CAT_SUCCESS',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',

}